export interface MedicalServiceItem {
  id: string;
  title: string;
  category: "mcu" | "lab" | "radiologi";
  categoryLabel: string;
  badge?: string;
  itemsCount: string;
  priceNumber: number;
  priceFormatted: string;
  description: string;
  itemsIncluded: string[];
}

export const CATALOG_SERVICES: MedicalServiceItem[] = [
  // ─── MCU PACKAGES (10) ──────────────────────────────────────────────────────
  {
    id: "mcu-hemat",
    title: "Paket MCU Hemat",
    category: "mcu",
    categoryLabel: "Medical Check-Up",
    badge: "TERPOPULER",
    itemsCount: "3 Service/Item",
    priceNumber: 250000,
    priceFormatted: "Rp 250.000",
    description: "Pemeriksaan kesehatan dasar hemat & efisien bagi individu.",
    itemsIncluded: ["Pemeriksaan Fisik Dokter Umum", "Hematologi Rutin (Hb, Leukosit, Trombosit)", "Urine Lengkap"],
  },
  {
    id: "mcu-pelajar",
    title: "Paket MCU Pelajar",
    category: "mcu",
    categoryLabel: "Medical Check-Up",
    badge: "REKOMENDASI",
    itemsCount: "3 Service/Item",
    priceNumber: 300000,
    priceFormatted: "Rp 300.000",
    description: "Khusus untuk syarat pendaftaran sekolah, kuliah, atau bebas narkoba.",
    itemsIncluded: ["Fisik & Visus Mata", "Tes Bebas Narkoba 5 Parameter", "Surat Keterangan Sehat Pelajar"],
  },
  {
    id: "mcu-pegawai",
    title: "Paket MCU Pegawai",
    category: "mcu",
    categoryLabel: "Medical Check-Up",
    badge: "TERPOPULER",
    itemsCount: "4 Service/Item",
    priceNumber: 450000,
    priceFormatted: "Rp 450.000",
    description: "Persyaratan tes kesehatan CPNS, BUMN, dan karyawan perusahaan.",
    itemsIncluded: ["Rontgen Thorax Digital", "Tes Bebas Narkoba 6 Parameter", "EKG Jantung Dasar", "Fisik Dokter Umum"],
  },
  {
    id: "mcu-calon-pengantin",
    title: "Paket MCU Calon Pengantin",
    category: "mcu",
    categoryLabel: "Medical Check-Up",
    badge: "REKOMENDASI",
    itemsCount: "4 Service/Item",
    priceNumber: 650000,
    priceFormatted: "Rp 650.000",
    description: "Pemeriksaan pranikah (Premarital Check Up) bagi calon pengantin.",
    itemsIncluded: ["Golongan Darah & Rhesus", "Skrining Thalassemia & Anemia", "HBsAg & HIV", "Skrining Kebidanan / Urologi"],
  },
  {
    id: "mcu-rohajj",
    title: "Paket MCU ROHAJJ (Haji / Umroh)",
    category: "mcu",
    categoryLabel: "Medical Check-Up",
    badge: "LENGKAP",
    itemsCount: "5 Service/Item",
    priceNumber: 750000,
    priceFormatted: "Rp 750.000",
    description: "Pemeriksaan kesehatan istitha'ah untuk calon jemaah Haji & Umroh.",
    itemsIncluded: ["Rontgen Thorax & EKG Jantung", "Laboratorium Darah Lengkap", "Tes Kehamilan (Wanita)", "Vaksin Meningitis & Influenza"],
  },
  {
    id: "mcu-silver",
    title: "Paket MCU Silver Eksekutif",
    category: "mcu",
    categoryLabel: "Medical Check-Up",
    badge: "REKOMENDASI",
    itemsCount: "6 Service/Item",
    priceNumber: 850000,
    priceFormatted: "Rp 850.000",
    description: "Paket skrining organ penting bagi dewasa muda.",
    itemsIncluded: ["Laboratorium Darah & Urine Lengkap", "Fungsi Hati & Ginjal (Ureum, Kreatinin)", "Profil Kolesterol & Gula Darah", "Rontgen Thorax"],
  },
  {
    id: "mcu-gold",
    title: "Paket MCU Gold Eksekutif",
    category: "mcu",
    categoryLabel: "Medical Check-Up",
    badge: "TERPOPULER",
    itemsCount: "8 Service/Item",
    priceNumber: 1350000,
    priceFormatted: "Rp 1.350.000",
    description: "Skrining kesehatan eksekutif menengah organ dalam.",
    itemsIncluded: ["Seluruh Fasilitas MCU Silver", "USG Abdomen / Perut", "Treadmill Test Jantung", "Konsultasi Dokter Spesialis Penyakit Dalam"],
  },
  {
    id: "mcu-platinum",
    title: "Paket MCU Platinum Eksekutif",
    category: "mcu",
    categoryLabel: "Medical Check-Up",
    badge: "LENGKAP",
    itemsCount: "10 Service/Item",
    priceNumber: 2100000,
    priceFormatted: "Rp 2.100.000",
    description: "Skrining komprehensif organ dalam & penanda tumor.",
    itemsIncluded: ["Seluruh Fasilitas MCU Gold", "Tumor Marker (CEA & AFP)", "CT-Scan Thorax / USG Mammografi", "Pemeriksaan Mata & THT"],
  },
  {
    id: "mcu-titanium",
    title: "Paket MCU Titanium VVIP",
    category: "mcu",
    categoryLabel: "Medical Check-Up",
    badge: "VIP",
    itemsCount: "12 Service/Item",
    priceNumber: 3500000,
    priceFormatted: "Rp 3.500.000",
    description: "Paket kualitatif terlengkap VVIP RSU Tangsel Care.",
    itemsIncluded: ["Seluruh Fasilitas MCU Platinum", "MRI 1.5 Tesla organ pilihan", "Ekokardiografi Jantung", "Kamar Rawat Transit VVIP 1 Hari"],
  },
  {
    id: "mcu-jantung",
    title: "Paket MCU Jantung Sehat",
    category: "mcu",
    categoryLabel: "Medical Check-Up",
    badge: "REKOMENDASI",
    itemsCount: "5 Service/Item",
    priceNumber: 1200000,
    priceFormatted: "Rp 1.200.000",
    description: "Skrining khusus kebugaran & potensi penyakit jantung koronari.",
    itemsIncluded: ["EKG Jantung 12 Lead", "Treadmill Stress Test", "Ekokardiografi USG Jantung", "Profil Lipid Lengkap & Konsultasi Spesialis Jantung"],
  },

  // ─── LAB SERVICES ─────────────────────────────────────────────────────────
  {
    id: "lab-hematologi-rutin",
    title: "Complete Blood Count (Hematologi Rutin)",
    category: "lab",
    categoryLabel: "Cek Laboratorium",
    badge: "TERPOPULER",
    itemsCount: "1 Service/Item",
    priceNumber: 134900,
    priceFormatted: "Rp 134.900",
    description: "Pemeriksaan hemoglobin, leukosit, hematokrit, trombosit, dan eritrosit.",
    itemsIncluded: ["Hemoglobin (Hb)", "Leukosit", "Trombosit", "Hematokrit", "Eritrosit"],
  },
  {
    id: "lab-cek-diabetes",
    title: "Paket Cek Diabetes & Gula Darah",
    category: "lab",
    categoryLabel: "Cek Laboratorium",
    badge: "REKOMENDASI",
    itemsCount: "3 Service/Item",
    priceNumber: 325650,
    priceFormatted: "Rp 325.650",
    description: "Skrining kadar gula darah puasa, 2 jam PP, dan HbA1c.",
    itemsIncluded: ["Gula Darah Puasa", "Gula Darah 2 Jam PP", "HbA1c (Rata-rata Gula Darah 3 Bulan)"],
  },
  {
    id: "lab-fungsi-hati",
    title: "Tes Fungsi Hati (SGOT & SGPT)",
    category: "lab",
    categoryLabel: "Cek Laboratorium",
    itemsCount: "2 Service/Item",
    priceNumber: 188700,
    priceFormatted: "Rp 188.700",
    description: "Pemeriksaan enzim hati untuk mendeteksi peradangan atau hepatitis.",
    itemsIncluded: ["SGOT (AST)", "SGPT (ALT)"],
  },
  {
    id: "lab-fungsi-ginjal",
    title: "Tes Fungsi Ginjal (Ureum & Kreatinin)",
    category: "lab",
    categoryLabel: "Cek Laboratorium",
    itemsCount: "2 Service/Item",
    priceNumber: 195000,
    priceFormatted: "Rp 195.000",
    description: "Pemeriksaan laju penyaringan ginjal dan pembuangan sisa asam urat/ureum.",
    itemsIncluded: ["Ureum", "Kreatinin", "Asam Urat"],
  },

  // ─── RADIOLOGI SERVICES ───────────────────────────────────────────────────
  {
    id: "rad-rontgen-thorax",
    title: "Cek Rontgen Thorax Digital",
    category: "radiologi",
    categoryLabel: "Cek Radiologi",
    badge: "TERPOPULER",
    itemsCount: "1 Service/Item",
    priceNumber: 220000,
    priceFormatted: "Rp 220.000",
    description: "Foto rontgen paru-paru dan jantung digital dosis radiasi rendah.",
    itemsIncluded: ["Foto X-Ray Thorax PA / AP", "Bacaan Dokter Spesialis Radiologi"],
  },
  {
    id: "rad-usg-abdomen",
    title: "Cek USG Abdomen Abdominal 4D",
    category: "radiologi",
    categoryLabel: "Cek Radiologi",
    badge: "REKOMENDASI",
    itemsCount: "1 Service/Item",
    priceNumber: 480000,
    priceFormatted: "Rp 480.000",
    description: "Pemeriksaan ultrasonografi organ perut (hati, empedu, ginjal, limpa, kandung kemih).",
    itemsIncluded: ["USG Perut / Abdomen Utuh", "Bacaan Dokter Spesialis Radiologi"],
  },
  {
    id: "rad-mri-head",
    title: "Cek MRI 1.5 Tesla Kepala / Otak",
    category: "radiologi",
    categoryLabel: "Cek Radiologi",
    badge: "LENGKAP",
    itemsCount: "1 Service/Item",
    priceNumber: 2400000,
    priceFormatted: "Rp 2.400.000",
    description: "Pencitraan MRI jaringan otak presisi tinggi untuk deteksi stroke atau kelainan saraf.",
    itemsIncluded: ["Scan MRI Brain 1.5 Tesla", "Bacaan Dokter Spesialis Radiologi"],
  },
];
